### PR TITLE
defaultValue property check

### PR DESCRIPTION
**Pull request by raxell**
Related to https://github.com/riot/compiler/issues/122
This should allow the distinction for using `.value` vs `setAttribute`

From the compiler side would become something like:
```js
export function createExpression(sourceNode, sourceFile, sourceCode, childNodeIndex) {
  switch (true) {
  case isTextNode(sourceNode):
    return textExpression(sourceNode, sourceFile, sourceCode, childNodeIndex)
  case isValueAttribute(sourceNode) && hasDefaultValueProperty(sourceNode):
    return valueExpression(sourceNode, sourceFile, sourceCode)
  case isEventAttribute(sourceNode):
    return eventExpression(sourceNode, sourceFile, sourceCode)
  default:
    return attributeExpression(sourceNode, sourceFile, sourceCode)
  }
}
```

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
Thank you for your pull request.
Here I list a few concerns:
1. this PR is a breaking change [since `<selects>` will stop working](https://plnkr.co/edit/zFULpRzHt4CibQxiTvsS?p=preview)
2. I don't get what's the benefit of detecting tags that have the `defaultValue` property
3. It doesn't solve any [real issue in the riot compiler](https://github.com/riot/compiler/issues/122#issuecomment-517909160)

**Comment by raxell** [comment]
> this PR is a breaking change since <selects> will stop working

Maybe, I'm not sure about this, will probably need more tests to verify that. `select` and all other tags will continue to have `value` attribute, it will just be setted using `setAttribute` instead of `.value`.

> I don't get what's the benefit of detecting tags that have the defaultValue property

The scope should be distinguish between setting `value` using `expressionTypes.VALUE` (for `input` and `textarea`) vs `expressionTypes.ATTRIBUTE` (for any other tag, e.g. `progress`).

**Comment by GianlucaGuarini** [comment]
Ok I've understood the issue. Thank for your PR but I don't want to overcomplicate this feature. I will make an exception only for the `<progress>` tag in the compiler

**Comment by raxell** [comment]
Ok, but the list of elements with value attributes is wrong. It's probably not worth to add it to this lib, it has been a misunderstanding

**Comment by GianlucaGuarini** [comment]
@raxell what's wrong in that list? 
That list contains https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes + [textarea](https://www.w3.org/TR/2010/WD-html5-20101019/the-button-element.html#the-textarea-element) + [output](https://www.w3.org/TR/2010/WD-html5-20101019/the-button-element.html#the-output-element) + [select](https://www.w3.org/TR/2010/WD-html5-20101019/the-button-element.html#the-select-element) all having the value attribute by specs

**Comment by raxell** [comment]
After looking at the patch seems ok, with value attribute you mean both attribute and property, by looking at it this way you're right.  
Initially I was thinking in a different way, we cleared it now.

**Pull request closed without merging**
